### PR TITLE
Assignment 2 @jdriscoll1 @alowe4

### PR DESCRIPTION
**Pull request by jdriscoll1**
https://happy-plant-0138e301e.3.azurestaticapps.net

### CODE REVIEW

**Comment by NicholasBurlakov** [comment]
Note: Custom CSS can only be used where specified.

Create a custom component to show available words ✅
* Im assuming that HintDialog is that component
Create/extend a word list component with a method called validWords that returns an array of valid words based on current guesses ❌
* i think you did this in HintDialog but the required name is validWords
Create unit tests for the validWords method ❌
* you do indeed have unit tests but they run for HintDialog, not validWords (which doesnt exist)
Display the number of valid words based on the entered letters ✅
When the number is clicked, show a dialog with all the available words with scrolling if there are too many to show on the screen. ✅
* It just takes a really long time because there are so many words but good job! it works!
When a word is clicked, the word should be entered as the guess but not submitted ✅
Add a hover over for the word so it is obvious that it can be clicked. (No CSS) ✅
Convert the sidebar to an App Bar ✅
* Beautiful hamburger menu
Name of the app on the left with an icon ✅
Choose an icon for the app (from Material Design or somewhere on the web) ✅
Clicking the name and icon of the app take you to the home page ✅
Hamburger menu on the right ✅
Menu option for an About page ✅
Create an About page that has a few sentences about this class project and how great Meg is ✅
Make sure this has a back button ✅
Add a settings dialog ✅
Add a settings selection to the App Bar's menu with a gear icon. This should open this dialog regardless of where you are on the site ✅
Option for dark and light mode ✅
Develop two additional color schemes (with creative names) and allow the user to change to them. Schemes should look good in both light and dark mode ✅
The above two items must be implemented with built in Veutify features ✅
Style the main game page ✅
Make it look like [wordle.com](https://www.nytimes.com/games/wordle/index.html) or the Wordle mobile app ❌
* So close! But its missing a ENTER and BACKSPACE key on the keyboard.
Add gradient to guesses blocks and keys (with CSS) ✅
Add drop shadow to keys (No CSS) ✅
Make the app responsive (No CSS) ✅
Include a link to your Azure App in your PR comments.
* Beautiful work. Great job for going the extra mile and adding 4 color schemes. Everything works as intended. Consider renaming to validWords and adding an ENTER and BACKSPACE key

**Review by schemcharger — COMMENTED** [review]
1. Create a custom component to show available words ✅
- Create/extend a word list component with a method called validWords that returns an array of valid words based on current guesses ✅
- Create unit tests for the validWords method ✅
- Display the number of valid words based on the entered letters ✅
- When the number is clicked, show a dialog with all the available words with scrolling if there are too many to show on the screen. ✅
- When a word is clicked, the word should be entered as the guess but not submitted ✅
- Add a hover over for the word so it is obvious that it can be clicked. (No CSS) ✅

2. Convert the sidebar to an App Bar ✅
- Name of the app on the left with an icon ✅
- Choose an icon for the app (from Material Design or somewhere on the web) ✅
- Clicking the name and icon of the app take you to the home page ✅
- Hamburger menu on the right ✅
- Menu option for an About page ✅
  - Create an About page that has a few sentences about this class project and how great Meg is ✅
  - Make sure this has a back button ✅

3. Add a settings dialog ✅
- Add a settings selection to the App Bar's menu with a gear icon. This should open this dialog regardless of where you are on the site ✅
- Option for dark and light mode ✅
- Develop two additional color schemes (with creative names) and allow the user to change to them. Schemes should look good in both light and dark mode ✅
- The above two items must be implemented with built in Veutify features ✅

4. Style the main game page ✅
- Make it look like [wordle.com](https://www.nytimes.com/games/wordle/index.html) or the Wordle mobile app ✅
- Add gradient to guesses blocks and keys (with CSS) ✅
- Add drop shadow to keys (No CSS) ✅
- Make the app responsive (No CSS) ✅

**Comment by jdriscoll1** [comment]
I apologize for the inconvenience, I accidentally deleted my Assignment-2 branch; thus closing the PR. I've reopened it and have made no changes.

**Review by mmwoodfo — COMMENTED** [review]
Great job!  Your word list works well!

**Pull request closed without merging**
