### PR TITLE
Assignment 5 - Hunter Thompson & Nolan Posey

### PR DESCRIPTION
**Pull request by StrangeRanger**
Link To PR: https://github.com/StrangeRanger/EWU-CSCD379-2023-Spring/pull/4

### CODE REVIEW

**Comment by AntonioGomez12** [comment]
EWU-CSCD378-2022-Spring
Assignment 5
The purpose of this assignment is to solidify your learning of:

Creating CRUD interface in a SPA with auth
ASP.NET Core Indentity
Use of JWTs as a bearer token
Using policy-based authorization
Features
Create an editor for the available words ✅
Create a page named "WordEditor" that allows words to be edited ✅
Support deleting a word ✅
Support adding a new word ✅
Editing words is not supported ✅ **Not supported when not master of the universe**
Duplicate words should not be allowed ✅
Support changing the common word boolean flag ✅
Words should be sorted alphabetically ✅
Provide a text box for searching words AS YOU TYPE which supports searching for words starting with letters specified ✅
Provide a menu item for navigating to the WordEditor page ✅
Anyone can look at the word list ✅
Word list is paginated (10-100 per page) ✅
Any logged in user can change the common word flag ✅
There is a login page/component/popup/etc for users to sign in ✅
Only users over 21 years of age (based on birthday) with a claim of MasterOfTheUniverse can add and remove words ✅
Users can be set up at start up in the API project as a seed (apriori), there does not need to be a sign up mechanism ✅
Turn in Process
On your fork, create an Assignment5 branch
Update this branch (Fetch upstream) from the Assignment5 branch in the class repo. [Assignment5 in class repo](https://github.com/IntelliTect-Samples/EWU-CSCD379-2022-Spring/tree/Assignment5)
Do your homework in your Assignment5 branch
Submit your pull request against Assignment5 in the class repo
Ask in Teams chat if you have questions or issues
Extra Credit
Find a bug in the application, create an issue, submit a pull request against the issue
Add the ability to sign up for an account by inputting an email and password
Allow the user to elevate their level of privelage by inputting a secret phrase
Select pagination record count

**Comment by AntonioGomez12** [comment]
Great job everything seems correct! Great implementation as well!

**Comment by slanante1997** [comment]
Awesome job! Thank you for providing the credentials for testing the log in and roles.

Create a page named "WordEditor" that allows words to be edited ✅
Support deleting a word ✅
Support adding a new word ✅
Editing words is not supported ✅
Duplicate words should not be allowed ✅
Support changing the common word boolean flag ✅
Words should be sorted alphabetically ✅
Provide a text box for searching words AS YOU TYPE which supports searching for words starting with letters specified ✅
Provide a menu item for navigating to the WordEditor page ✅
Anyone can look at the word list ✅
Word list is paginated (10-100 per page) ✅
Any logged in user can change the common word flag ✅
There is a login page/component/popup/etc for users to sign in ✅
Only users over 21 years of age (based on birthday) with a claim of MasterOfTheUniverse can add and remove words ✅
Users can be set up at start up in the API project as a seed (apriori), there does not need to be a sign up mechanism✅

**Comment by meghanmae** [comment]
Not sure if I'm missing something... but I don't see a place on your website to be able to edit, delete or add words. I also don't see any auth policies set up in your code? The PR reviews from everyone seem to say that you've completed the assignment with no issues though.

**Comment by Nolan-Posey** [comment]
> Not sure if I'm missing something... but I don't see a place on your website to be able to edit, delete or add words. I also don't see any auth policies set up in your code? The PR reviews from everyone seem to say that you've completed the assignment with no issues though.

@mmwoodfo Hey Meg! Sorry I didn't respond sooner. In the PR that was linked to this PR, we left a comment at the top giving the sign in information for two users. One with the MOTU claim and one without the claim. In the pop out menu there is a button that will take you to the word editor, once there anyone has the ability to flip the commonality of a word but only users who have the MOTU claim can even see the buttons to delete or add a word. 

As for the policies, we didn't set up a policy in the file that was provided for us. We instead prevented the user from being able to access the buttons to add or remove words if their token didn't contain the MOTU role. In hind sight we also could added protection to the controllers by requiring a user to have those roles in order to access the endpoint, similar to how Grant showed us in class. 

Hope this helps!

-Nolan Posey

**Pull request closed without merging**
